import { createHash } from 'node:crypto';
import type { OperatingRecordScope } from '../shared/revenue-ops-contracts';
import type { BusinessDatabase, StoredAutomationFailure, StoredAutomationSchedule, StoredAutomationSchedulerAction, StoredAutomationTrigger } from './database';
import { evaluateAutomationSchedule, type AutomationSchedule, type AutomationSchedulerAction, type AutomationSchedulerFailure, type ScheduleTriggerRecord } from '../domain/automation-schedules';

function checksum(payloadJson: string): string { return createHash('sha256').update(payloadJson, 'utf8').digest('hex'); }
function decode(record: StoredAutomationSchedule): AutomationSchedule { if (checksum(record.payloadJson) !== record.payloadChecksum) throw new Error(`Automation schedule ${record.id} failed checksum verification.`); return JSON.parse(record.payloadJson) as AutomationSchedule; }
function stored(scope: OperatingRecordScope, schedule: AutomationSchedule, updatedAt: string): StoredAutomationSchedule { const payloadJson = JSON.stringify(schedule); return { id: schedule.id, companyId: scope.companyId, branchId: scope.branchId, payloadJson, payloadChecksum: checksum(payloadJson), version: schedule.version, createdAt: updatedAt, updatedAt }; }

export class AutomationScheduleStore {
  public constructor(private readonly database: BusinessDatabase) {}

  public save(scope: OperatingRecordScope, schedule: AutomationSchedule, updatedAt = new Date().toISOString()): AutomationSchedule { if (schedule.scope.companyId !== scope.companyId || schedule.scope.branchId !== scope.branchId) throw new Error('Automation schedule is outside the active scope.'); this.database.upsertAutomationSchedule(stored(scope, schedule, updatedAt)); return schedule; }
  public list(scope: OperatingRecordScope): AutomationSchedule[] { return this.database.listAutomationSchedules(scope.companyId, scope.branchId).map(decode); }
  public listTriggerHistory(scope: OperatingRecordScope, scheduleId?: string): ScheduleTriggerRecord[] { return this.database.listAutomationTriggers(scope.companyId, scope.branchId, scheduleId).map((record) => { if (checksum(record.payloadJson) !== record.payloadChecksum) throw new Error(`Automation trigger ${record.id} failed checksum verification.`); const parsed = JSON.parse(record.payloadJson) as ScheduleTriggerRecord; return { ...parsed, scheduleId: record.scheduleId, slotKey: record.slotKey }; }); }
  public recordFailure(scope: OperatingRecordScope, result: ScheduleTriggerRecord, reason: string, updatedAt = new Date().toISOString()): AutomationSchedulerFailure { if (result.decision !== 'due') throw new Error('Only due schedule results can be dead-lettered.'); const payloadJson = JSON.stringify(result); const record: StoredAutomationFailure = { id: `${result.scheduleId}:${result.slotKey}`, scheduleId: result.scheduleId, companyId: scope.companyId, branchId: scope.branchId, slotKey: result.slotKey, reason: reason.trim(), attempts: 1, status: 'open', payloadJson, payloadChecksum: checksum(payloadJson), createdAt: updatedAt, updatedAt }; this.database.upsertAutomationFailure(record); return this.listFailures(scope).find(({ id }) => id === record.id)!; }
  public listFailures(scope: OperatingRecordScope, status?: AutomationSchedulerFailure['status']): AutomationSchedulerFailure[] { return this.database.listAutomationFailures(scope.companyId, scope.branchId, status).map((record) => { if (checksum(record.payloadJson) !== record.payloadChecksum) throw new Error(`Automation scheduler failure ${record.id} failed checksum verification.`); return { id: record.id, scheduleId: record.scheduleId, slotKey: record.slotKey, reason: record.reason, attempts: record.attempts, status: record.status, createdAt: record.createdAt, updatedAt: record.updatedAt, resolvedAt: record.resolvedAt, resolutionReference: record.resolutionReference }; }); }
  public getFailureTrigger(scope: OperatingRecordScope, failureId: string): ScheduleTriggerRecord { const record = this.database.listAutomationFailures(scope.companyId, scope.branchId).find(({ id }) => id === failureId); if (!record) throw new Error('Automation scheduler failure is outside the active scope.'); if (checksum(record.payloadJson) !== record.payloadChecksum) throw new Error(`Automation scheduler failure ${record.id} failed checksum verification.`); return JSON.parse(record.payloadJson) as ScheduleTriggerRecord; }
  public recordAction(scope: OperatingRecordScope, failureId: string, action: StoredAutomationSchedulerAction['action'], actorId: string, reason: string, createdAt = new Date().toISOString()): AutomationSchedulerAction { const payload = { failureId, action, actorId, reason: reason.trim(), createdAt }; const payloadJson = JSON.stringify(payload); const record: StoredAutomationSchedulerAction = { id: `scheduler-action-${createHash('sha256').update(`${failureId}:${action}:${actorId}:${createdAt}:${reason}`, 'utf8').digest('hex').slice(0, 24)}`, failureId, companyId: scope.companyId, branchId: scope.branchId, action, actorId, reason: reason.trim(), payloadJson, payloadChecksum: checksum(payloadJson), createdAt }; this.database.recordAutomationSchedulerAction(record); return { id: record.id, ...payload };
  }
  public listActions(scope: OperatingRecordScope, failureId?: string): AutomationSchedulerAction[] { return this.database.listAutomationSchedulerActions(scope.companyId, scope.branchId, failureId).map((record) => { if (checksum(record.payloadJson) !== record.payloadChecksum) throw new Error(`Automation scheduler action ${record.id} failed checksum verification.`); return { id: record.id, failureId: record.failureId, action: record.action, actorId: record.actorId, reason: record.reason, createdAt: record.createdAt }; }); }
  public resolveFailure(scope: OperatingRecordScope, id: string, resolutionReference: string, resolvedAt = new Date().toISOString()): AutomationSchedulerFailure { this.database.resolveAutomationFailure(scope.companyId, scope.branchId, id, resolvedAt, resolutionReference.trim()); const resolved = this.listFailures(scope).find(({ id: failureId }) => failureId === id); if (!resolved) throw new Error('Resolved scheduler failure could not be reloaded.'); return resolved; }
  public preview(scope: OperatingRecordScope, scheduleId: string, now = new Date()): ScheduleTriggerRecord { const schedule = this.list(scope).find(({ id }) => id === scheduleId); if (!schedule) throw new Error('Automation schedule is outside the active scope.'); const consumed = new Set(this.database.listAutomationTriggerSlots(scope.companyId, scope.branchId, schedule.id)); return evaluateAutomationSchedule(schedule, now, consumed); }
  public persistTrigger(scope: OperatingRecordScope, result: ScheduleTriggerRecord): ScheduleTriggerRecord { if (result.decision !== 'due') return result; const payloadJson = JSON.stringify(result); const trigger: StoredAutomationTrigger = { id: `${result.scheduleId}:${result.slotKey}`, scheduleId: result.scheduleId, companyId: scope.companyId, branchId: scope.branchId, slotKey: result.slotKey, payloadJson, payloadChecksum: checksum(payloadJson), createdAt: result.dueAt }; const inserted = this.database.recordAutomationTrigger(trigger); return inserted ? result : { ...result, decision: 'deduplicated', reason: 'This schedule slot already produced a trigger.' }; }
  public evaluate(scope: OperatingRecordScope, scheduleId: string, now = new Date()): ScheduleTriggerRecord { return this.persistTrigger(scope, this.preview(scope, scheduleId, now)); }
}
