from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "output" / "pdf" / "epic-bos-india-quotation.pdf"

INK = colors.HexColor("#102B2C")
COPPER = colors.HexColor("#D9672B")
GOLD = colors.HexColor("#F0B84B")
TEAL = colors.HexColor("#1A6D62")
MUTED = colors.HexColor("#617371")
LINE = colors.HexColor("#D5E0DC")
PALE = colors.HexColor("#F5F8F7")
NOTICE = colors.HexColor("#FFF8E9")


def money(value: float) -> str:
    # ASCII-safe Rs label; the in-app PDF uses the locale-aware INR symbol.
    whole, fraction = f"{value:,.2f}".split(".")
    groups = whole.split(",")
    if len(groups) > 2:
        last = groups[-1]
        head = "".join(groups[:-1])
        pairs = []
        while len(head) > 3:
            pairs.insert(0, head[-2:])
            head = head[:-2]
        if head:
            pairs.insert(0, head)
        whole = ",".join(pairs + [last])
    return f"Rs {whole}.{fraction}"


def header_footer(canvas, doc):
    width, height = A4
    canvas.saveState()
    canvas.setFillColor(COPPER)
    canvas.rect(0, height - 3 * mm, width * 0.36, 3 * mm, stroke=0, fill=1)
    canvas.setFillColor(GOLD)
    canvas.rect(width * 0.36, height - 3 * mm, width * 0.33, 3 * mm, stroke=0, fill=1)
    canvas.setFillColor(TEAL)
    canvas.rect(width * 0.69, height - 3 * mm, width * 0.31, 3 * mm, stroke=0, fill=1)
    canvas.setStrokeColor(LINE)
    canvas.line(18 * mm, 15 * mm, width - 18 * mm, 15 * mm)
    canvas.setFillColor(MUTED)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(18 * mm, 10 * mm, "Generated by Epic BOS Commercial Foundry")
    page = f"Page {doc.page}"
    canvas.drawString(width - 18 * mm - stringWidth(page, "Helvetica", 7), 10 * mm, page)
    canvas.restoreState()


def build():
    styles = getSampleStyleSheet()
    body = ParagraphStyle("Body", parent=styles["BodyText"], fontName="Helvetica", fontSize=8.5, leading=12, textColor=INK)
    small = ParagraphStyle("Small", parent=body, fontSize=7.3, leading=10, textColor=MUTED)
    label = ParagraphStyle("Label", parent=small, fontName="Helvetica-Bold", fontSize=6.8, leading=9, textColor=MUTED, spaceAfter=4)
    right = ParagraphStyle("Right", parent=body, alignment=TA_RIGHT)
    title = ParagraphStyle("Title", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=24, leading=26, textColor=INK, alignment=TA_RIGHT)
    brand = ParagraphStyle("Brand", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=18, leading=22, textColor=INK)
    eyebrow = ParagraphStyle("Eyebrow", parent=label, textColor=COPPER, fontSize=7.5, leading=10)

    doc = SimpleDocTemplate(
        str(OUTPUT), pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=15 * mm, bottomMargin=22 * mm, title="Epic BOS India Quotation",
        author="Epic BOS Commercial Foundry", subject="Governed commercial quotation sample",
    )
    story = []
    mast = Table([
        [Paragraph("COMMERCIAL FOUNDRY", eyebrow), Paragraph("QUOTATION", title)],
        [Paragraph("Epic BOS India", brand), Paragraph("QTN-26-27-00001 / Revision 1", right)],
        [Paragraph("Epic BOS India Private Limited<br/>GSTIN: 27ABCDE1234F1Z5", small), Paragraph("APPROVED", ParagraphStyle("Status", parent=right, textColor=TEAL, fontName="Helvetica-Bold"))],
    ], colWidths=[100 * mm, 74 * mm])
    mast.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("BOTTOMPADDING", (0, 0), (-1, -1), 4), ("LINEBELOW", (0, -1), (-1, -1), .6, LINE), ("BOTTOMPADDING", (0, -1), (-1, -1), 11)]))
    story += [mast, Spacer(1, 7 * mm)]

    parties = Table([
        [Paragraph("PREPARED FOR", label), Paragraph("COMMERCIAL CONTACT", label)],
        [Paragraph("Sahyadri Distribution Network", ParagraphStyle("Party", parent=body, fontName="Helvetica-Bold", fontSize=11)), Paragraph("Ananya Rao", ParagraphStyle("Party2", parent=body, fontName="Helvetica-Bold", fontSize=11))],
        [Paragraph("Sahyadri Distribution Network Private Limited", small), Paragraph("ananya.rao@example.in", small)],
    ], colWidths=[87 * mm, 87 * mm])
    parties.setStyle(TableStyle([("BOX", (0, 0), (-1, -1), .6, LINE), ("INNERGRID", (0, 0), (-1, -1), .6, LINE), ("BACKGROUND", (0, 0), (-1, -1), PALE), ("LEFTPADDING", (0, 0), (-1, -1), 10), ("RIGHTPADDING", (0, 0), (-1, -1), 10), ("TOPPADDING", (0, 0), (-1, -1), 7), ("BOTTOMPADDING", (0, 0), (-1, -1), 7)]))
    story += [parties, Spacer(1, 5 * mm)]

    facts = Table([
        [Paragraph("VALID UNTIL", label), Paragraph("PLACE OF SUPPLY", label), Paragraph("RECIPIENT", label), Paragraph("CURRENCY", label)],
        [Paragraph("31 August 2026", body), Paragraph("Maharashtra / 27", body), Paragraph("GST registered", body), Paragraph("INR", body)],
    ], colWidths=[43.5 * mm] * 4)
    facts.setStyle(TableStyle([("BOX", (0, 0), (-1, -1), .6, LINE), ("INNERGRID", (0, 0), (-1, -1), .6, LINE), ("BACKGROUND", (0, 0), (-1, -1), PALE), ("LEFTPADDING", (0, 0), (-1, -1), 8), ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 7)]))
    story += [facts, Spacer(1, 7 * mm)]

    rows = [["#", "PRODUCT / CLASSIFICATION", "GST", "DISCOUNT", "TAXABLE"]]
    rows.append([
        "1", Paragraph("<b>Distributor operations platform</b><br/><font color='#617371'>SAC 998314 - 1 x Rs 48,00,000.00</font>", body),
        "18%", money(120000), money(4680000),
    ])
    lines = Table(rows, colWidths=[9 * mm, 81 * mm, 18 * mm, 32 * mm, 34 * mm], repeatRows=1)
    lines.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), INK), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, 0), 7), ("ALIGN", (2, 1), (-1, -1), "RIGHT"), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LINEBELOW", (0, 1), (-1, -1), .6, LINE), ("LEFTPADDING", (0, 0), (-1, -1), 8), ("RIGHTPADDING", (0, 0), (-1, -1), 8), ("TOPPADDING", (0, 0), (-1, -1), 9), ("BOTTOMPADDING", (0, 0), (-1, -1), 9)]))
    story += [lines, Spacer(1, 6 * mm)]

    summary = Table([
        ["List subtotal", money(4800000)],
        ["Partner launch concession", f"- {money(120000)}"],
        ["CGST", money(421200)],
        ["SGST", money(421200)],
        [Paragraph("<b>GRAND TOTAL</b>", body), Paragraph(f"<b>{money(5522400)}</b>", right)],
    ], colWidths=[48 * mm, 43 * mm], hAlign="RIGHT")
    summary.setStyle(TableStyle([("ALIGN", (1, 0), (1, -1), "RIGHT"), ("TEXTCOLOR", (0, 0), (-1, -2), MUTED), ("FONTNAME", (0, 0), (-1, -2), "Helvetica"), ("FONTSIZE", (0, 0), (-1, -2), 8), ("LINEBELOW", (0, 0), (-1, -2), .5, LINE), ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#EDF4F1")), ("BOX", (0, -1), (-1, -1), .6, LINE), ("LEFTPADDING", (0, 0), (-1, -1), 8), ("RIGHTPADDING", (0, 0), (-1, -1), 8), ("TOPPADDING", (0, 0), (-1, -1), 7), ("BOTTOMPADDING", (0, 0), (-1, -1), 7)]))
    story += [summary, Spacer(1, 8 * mm)]

    notice = Table([[Paragraph("<b>Commercial tax preview</b><br/>This quotation is not a tax invoice. HSN/SAC classification and GST treatment are governed reference data and must be verified for the actual supply before invoicing.", body)]], colWidths=[174 * mm])
    notice.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), NOTICE), ("LINEBEFORE", (0, 0), (0, -1), 3, GOLD), ("LEFTPADDING", (0, 0), (-1, -1), 11), ("RIGHTPADDING", (0, 0), (-1, -1), 11), ("TOPPADDING", (0, 0), (-1, -1), 9), ("BOTTOMPADDING", (0, 0), (-1, -1), 9)]))
    story += [notice]
    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)


if __name__ == "__main__":
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    build()
    print(OUTPUT)
