import { contextBridge, ipcRenderer } from 'electron';
import type { EpicBosBridge } from './shared/contracts';
import { IPC_CHANNELS } from './shared/contracts';

const bridge: EpicBosBridge = {
  system: {
    getInfo: () => ipcRenderer.invoke(IPC_CHANNELS.systemInfo),
    getBuildProvenance: () => ipcRenderer.invoke(IPC_CHANNELS.systemBuildProvenance),
  },
  auth: {
    getStatus: () => ipcRenderer.invoke(IPC_CHANNELS.authStatus),
    bootstrapOwner: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.authBootstrapOwner, input),
    login: (input) => ipcRenderer.invoke(IPC_CHANNELS.authLogin, input),
    logout: () => ipcRenderer.invoke(IPC_CHANNELS.authLogout),
    lock: () => ipcRenderer.invoke(IPC_CHANNELS.authLock),
    changePassword: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.authChangePassword, input),
  },
  storage: {
    listAttachments: (target) =>
      ipcRenderer.invoke(IPC_CHANNELS.storageListAttachments, target),
    addAttachment: (target) =>
      ipcRenderer.invoke(IPC_CHANNELS.storageAddAttachment, target),
    exportAttachment: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.storageExportAttachment, input),
    createDatabaseBackup: () =>
      ipcRenderer.invoke(IPC_CHANNELS.storageCreateDatabaseBackup),
    restoreDatabaseBackup: () =>
      ipcRenderer.invoke(IPC_CHANNELS.storageRestoreDatabaseBackup),
    listRestoreDrills: () =>
      ipcRenderer.invoke(IPC_CHANNELS.storageListRestoreDrills),
    runRestoreDrill: () =>
      ipcRenderer.invoke(IPC_CHANNELS.storageRunRestoreDrill),
  },
  retailWorkspace: {
    getStatus: () => ipcRenderer.invoke(IPC_CHANNELS.retailWorkspaceGetStatus),
    getDemoResetPreview: () =>
      ipcRenderer.invoke(IPC_CHANNELS.retailWorkspaceGetDemoResetPreview),
    applyDemoReset: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.retailWorkspaceApplyDemoReset, input),
  },
  integration: {
    listApiKeys: (scope) => ipcRenderer.invoke(IPC_CHANNELS.integrationListApiKeys, scope),
    issueApiKey: (input) => ipcRenderer.invoke(IPC_CHANNELS.integrationIssueApiKey, input),
    revokeApiKey: (input) => ipcRenderer.invoke(IPC_CHANNELS.integrationRevokeApiKey, input),
    exportApiKeyInventory: (scope) => ipcRenderer.invoke(IPC_CHANNELS.integrationExportApiKeyInventory, scope),
    exportProviderCertificationPackage: (input) => ipcRenderer.invoke(IPC_CHANNELS.integrationExportProviderCertification, input),
    getRetailCertificationPack: () => ipcRenderer.invoke(IPC_CHANNELS.integrationGetRetailCertificationPack),
    exportRetailCertificationPack: () => ipcRenderer.invoke(IPC_CHANNELS.integrationExportRetailCertificationPack),
  },
  release: {
    listGates: () => ipcRenderer.invoke(IPC_CHANNELS.releaseListGates),
    recordGate: (input) => ipcRenderer.invoke(IPC_CHANNELS.releaseRecordGate, input),
    listArtifactEvidence: () => ipcRenderer.invoke(IPC_CHANNELS.releaseListArtifactEvidence),
    recordArtifactEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.releaseRecordArtifactEvidence, input),
    decideArtifactEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.releaseDecideArtifactEvidence, input),
    listUpdateEvidence: () => ipcRenderer.invoke(IPC_CHANNELS.releaseListUpdateEvidence),
    recordUpdateEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.releaseRecordUpdateEvidence, input),
    decideUpdateEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.releaseDecideUpdateEvidence, input),
    getAutoUpdateStatus: () => ipcRenderer.invoke(IPC_CHANNELS.releaseAutoUpdateStatus),
    listUiAcceptanceEvidence: () => ipcRenderer.invoke(IPC_CHANNELS.releaseListUiAcceptanceEvidence),
    recordUiAcceptanceEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.releaseRecordUiAcceptanceEvidence, input),
    decideUiAcceptanceEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.releaseDecideUiAcceptanceEvidence, input),
    getUiAcceptanceReadiness: () => ipcRenderer.invoke(IPC_CHANNELS.releaseUiAcceptanceReadiness),
    getReadiness: () => ipcRenderer.invoke(IPC_CHANNELS.releaseReadiness),
    createReadinessReport: () => ipcRenderer.invoke(IPC_CHANNELS.releaseReadinessReport),
    createSupportDiagnostics: () => ipcRenderer.invoke(IPC_CHANNELS.releaseSupportDiagnostics),
  },
  intelligence: {
    listAnomalies: () => ipcRenderer.invoke(IPC_CHANNELS.intelligenceListAnomalies),
    saveAnomaly: (input) => ipcRenderer.invoke(IPC_CHANNELS.intelligenceSaveAnomaly, input),
    reviewAnomaly: (input) => ipcRenderer.invoke(IPC_CHANNELS.intelligenceReviewAnomaly, input),
    listReportExecutions: () => ipcRenderer.invoke(IPC_CHANNELS.intelligenceListReportExecutions),
    saveReportExecution: (input) => ipcRenderer.invoke(IPC_CHANNELS.intelligenceSaveReportExecution, input),
    listReportDeliveryPlans: () => ipcRenderer.invoke(IPC_CHANNELS.intelligenceListReportDeliveryPlans),
    listReportDeliveryAttempts: () => ipcRenderer.invoke(IPC_CHANNELS.intelligenceListReportDeliveryAttempts),
    createReportDeliveryPlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.intelligenceCreateReportDeliveryPlan, input),
    decideReportDeliveryPlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.intelligenceDecideReportDeliveryPlan, input),
    prepareReportDeliveryAttempt: (input) => ipcRenderer.invoke(IPC_CHANNELS.intelligencePrepareReportDeliveryAttempt, input),
    recordReportDeliveryResult: (input) => ipcRenderer.invoke(IPC_CHANNELS.intelligenceRecordReportDeliveryResult, input),
  },
  automation: {
    listRuns: () => ipcRenderer.invoke(IPC_CHANNELS.automationListRuns),
    proposeRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationProposeRun, input),
    approveRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationApproveRun, input),
    startRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationStartRun, input),
    retryRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationRetryRun, input),
    completeRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationCompleteRun, input),
  },
  automationSchedules: {
    list: () => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleList),
    listTriggerHistory: () => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleTriggerHistory),
    listFailures: () => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleFailures),
    resolveFailure: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleResolveFailure, input),
    getOperations: () => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleOperations),
    retryFailure: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleRetryFailure, input),
    acknowledgeEscalation: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleAcknowledgeEscalation, input),
    listActions: () => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleActions),
    save: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleSave, input),
    evaluate: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleEvaluate, input),
    tick: (input) => ipcRenderer.invoke(IPC_CHANNELS.automationScheduleTick, input),
  },
  party: {
    getSnapshot: () => ipcRenderer.invoke(IPC_CHANNELS.partySnapshot),
    createAccount: (input) => ipcRenderer.invoke(IPC_CHANNELS.partyCreateAccount, input),
    createContact: (input) => ipcRenderer.invoke(IPC_CHANNELS.partyCreateContact, input),
    recordConsent: (input) => ipcRenderer.invoke(IPC_CHANNELS.partyRecordConsent, input),
    resolveDuplicate: (input) => ipcRenderer.invoke(IPC_CHANNELS.partyResolveDuplicate, input),
    addAddress: (input) => ipcRenderer.invoke(IPC_CHANNELS.partyAddAddress, input),
    addContactPoint: (input) => ipcRenderer.invoke(IPC_CHANNELS.partyAddContactPoint, input),
    createRelationship: (input) => ipcRenderer.invoke(IPC_CHANNELS.partyCreateRelationship, input),
    executeMerge: (input) => ipcRenderer.invoke(IPC_CHANNELS.partyExecuteMerge, input),
    convertLead: (input) => ipcRenderer.invoke(IPC_CHANNELS.partyConvertLead, input),
  },
  crmDepth: {
    getSnapshot: () => ipcRenderer.invoke(IPC_CHANNELS.crmDepthSnapshot),
    updatePipeline: (input) => ipcRenderer.invoke(IPC_CHANNELS.crmDepthUpdatePipeline, input),
    createScoringRule: (input) => ipcRenderer.invoke(IPC_CHANNELS.crmDepthCreateScoringRule, input),
    createCampaign: (input) => ipcRenderer.invoke(IPC_CHANNELS.crmDepthCreateCampaign, input),
    transitionCampaign: (input) => ipcRenderer.invoke(IPC_CHANNELS.crmDepthTransitionCampaign, input),
    createSavedView: (input) => ipcRenderer.invoke(IPC_CHANNELS.crmDepthCreateSavedView, input),
    previewLeadImport: () => ipcRenderer.invoke(IPC_CHANNELS.crmDepthPreviewLeadImport),
    commitImport: (input) => ipcRenderer.invoke(IPC_CHANNELS.crmDepthCommitImport, input),
    configureAdapter: (input) => ipcRenderer.invoke(IPC_CHANNELS.crmDepthConfigureAdapter, input),
    recordCommunication: (input) => ipcRenderer.invoke(IPC_CHANNELS.crmDepthRecordCommunication, input),
    recordCommunicationDelivery: (input) => ipcRenderer.invoke(IPC_CHANNELS.crmDepthRecordCommunicationDelivery, input),
  },
  generalLedger: {
    getSnapshot: () => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerSnapshot),
    bindCompany: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerBindCompany, input),
    createJournal: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerCreateJournal, input),
    prepareRevenueInvoicePosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareRevenueInvoicePosting, input),
    prepareCashReceiptPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareCashReceiptPosting, input),
    prepareWriteOffPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareWriteOffPosting, input),
    prepareWithholdingPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareWithholdingPosting, input),
    prepareTreasuryPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareTreasuryPosting, input),
    prepareManufacturingPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareManufacturingPosting, input),
    prepareLandedCostPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareLandedCostPosting, input),
    prepareRetailSaleCostPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareRetailSaleCostPosting, input),
    prepareRetailReturnCostPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareRetailReturnCostPosting, input),
    prepareRetailCommerceSettlementPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareRetailCommerceSettlementPosting, input),
    prepareRetailCommissionPayoutPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareRetailCommissionPayoutPosting, input),
    preparePeoplePosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPreparePeoplePosting, input),
    prepareCommercialAdjustmentPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareCommercialAdjustmentPosting, input),
    prepareSupplierInvoicePosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareSupplierInvoicePosting, input),
    prepareAssetCapitalizationPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareAssetCapitalizationPosting, input),
    prepareAssetDepreciationPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareAssetDepreciationPosting, input),
    prepareAssetRetirementPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareAssetRetirementPosting, input),
    prepareAssetSaleDisposalPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareAssetSaleDisposalPosting, input),
    prepareAssetLifecyclePosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareAssetLifecyclePosting, input),
    prepareProjectRevenueRecognitionPosting: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPrepareProjectRevenueRecognitionPosting, input),
    postJournal: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerPostJournal, input),
    reverseJournal: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerReverseJournal, input),
    cancelReversalJournal: (input) => ipcRenderer.invoke(IPC_CHANNELS.generalLedgerCancelReversalJournal, input),
  },
  financeCompletion: {
    list: () => ipcRenderer.invoke(IPC_CHANNELS.financeCompletionList),
    save: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeCompletionSave, input),
  },
  revenueOps: {
    getSnapshot: () => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsSnapshot),
    listRetailCutoverPlans: () => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsListRetailCutoverPlans),
    fetchRetailHubCutoverAssessment: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsFetchRetailHubCutoverAssessment, input),
    createRetailCutoverPlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateRetailCutoverPlan, input),
    createRetailCutoverPlanFromHubAssessment: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateRetailCutoverPlanFromHubAssessment, input),
    advanceRetailCutover: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsAdvanceRetailCutover, input),
    getPeopleReadProjection: () => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsPeopleReadProjection),
    updateProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsUpdateProfile, input),
    createTerritory: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateTerritory, input),
    createAssignmentRule: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateAssignmentRule, input),
    bulkAssign: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsBulkAssign, input),
    createSegment: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateSegment, input),
    createOpportunity: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateOpportunity, input),
    createQuote: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateQuote, input),
    transitionQuote: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsTransitionQuote, input),
    createGstTaxCode: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateGstTaxCode, input),
    createCatalogProduct: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateCatalogProduct, input),
    importRetailProductPack: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsImportRetailProductPack, input),
    createPriceList: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreatePriceList, input),
    createPriceListEntry: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreatePriceListEntry, input),
    createDiscountPolicy: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateDiscountPolicy, input),
    submitPriceListForApproval: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsSubmitPriceListForApproval, input),
    decidePriceListApproval: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsDecidePriceListApproval, input),
    submitQuoteForApproval: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsSubmitQuoteForApproval, input),
    decideQuoteApproval: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsDecideQuoteApproval, input),
    exportQuotePdf: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsExportQuotePdf, input),
    convertQuoteToSalesOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsConvertQuoteToSalesOrder, input),
    transitionSalesOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsTransitionSalesOrder, input),
    updateFulfilmentTask: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsUpdateFulfilmentTask, input),
    createPaymentTerm: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreatePaymentTerm, input),
    createRetailCounter: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCounter, input),
    openRetailCashierShift: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailOpenCashierShift, input),
    checkoutRetailSale: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCheckout, input),
    enqueueRetailOfflineSale: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailEnqueueOfflineSale, input),
    syncRetailOfflineSale: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailSyncOfflineSale, input),
    syncRetailOfflineQueue: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailSyncOfflineQueue, input),
    resolveRetailOfflineSale: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailResolveOfflineSale, input),
    ingestRetailUnifiedOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailIngestUnifiedOrder, input),
    prepareRetailUnifiedOrderHandoff: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPrepareUnifiedOrderHandoff, input),
    prepareRetailOrderHubHandoff: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPrepareOrderHubHandoff, input),
    recordRetailOrderHubHandoffResult: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRecordOrderHubHandoffResult, input),
    prepareRetailOrderFulfilmentHandoff: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPrepareOrderFulfilmentHandoff, input),
    decideRetailOrderFulfilmentHandoff: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideOrderFulfilmentHandoff, input),
    reserveRetailUnifiedOrderStock: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailReserveUnifiedOrderStock, input),
    createRetailUnifiedOrderPickTasks: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateUnifiedOrderPickTasks, input),
    completeRetailUnifiedOrderPickTasks: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCompleteUnifiedOrderPickTasks, input),
    createRetailUnifiedOrderShipmentPackage: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateUnifiedOrderShipmentPackage, input),
    completeRetailUnifiedOrderShipmentPackage: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCompleteUnifiedOrderShipmentPackage, input),
    prepareRetailUnifiedOrderDispatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPrepareUnifiedOrderDispatch, input),
    dispatchRetailUnifiedOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDispatchUnifiedOrder, input),
    confirmRetailUnifiedOrderDelivery: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailConfirmUnifiedOrderDelivery, input),
    reconcileRetailUnifiedOrderRto: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailReconcileUnifiedOrderRto, input),
    reconcileRetailUnifiedOrderReturn: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailReconcileUnifiedOrderReturn, input),
    recordRetailUnifiedOrderCarrierCallback: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRecordUnifiedOrderCarrierCallback, input),
    prepareRetailDeviceTransport: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPrepareDeviceTransport, input),
    recordRetailDeviceTransport: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRecordDeviceTransport, input),
    recordRetailNativeDeviceDriverResult: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRecordNativeDeviceDriverResult, input),
    executeRetailDeviceTransport: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailExecuteDeviceTransport, input),
    retryRetailDeviceTransport: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRetryDeviceTransport, input),
    preflightRetailDeviceTransport: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPreflightDeviceTransport, input),
    recordRetailDevicePreflightEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRecordDevicePreflightEvidence, input),
    createRetailDeviceAdapterProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateDeviceAdapterProfile, input),
    approveRetailDeviceAdapterProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailApproveDeviceAdapterProfile, input),
    recordRetailDeviceAdapterAcknowledgement: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRecordDeviceAdapterAcknowledgement, input),
    activateRetailDeviceAdapterProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailActivateDeviceAdapterProfile, input),
    suspendRetailDeviceAdapterProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailSuspendDeviceAdapterProfile, input),
    createRetailLoyaltyAccount: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateLoyaltyAccount, input),
    redeemRetailLoyaltyPoints: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRedeemLoyaltyPoints, input),
    createRetailCustomerVisit: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCustomerVisit, input),
    linkRetailCustomerVisitToSale: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailLinkCustomerVisitToSale, input),
    createRetailSalesCommission: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateSalesCommission, input),
    decideRetailSalesCommission: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideSalesCommission, input),
    payRetailSalesCommission: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPaySalesCommission, input),
    createRetailCommissionPayoutBatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCommissionPayoutBatch, input),
    decideRetailCommissionPayoutBatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideCommissionPayoutBatch, input),
    releaseRetailCommissionPayoutBatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailReleaseCommissionPayoutBatch, input),
    requestRetailCashierShiftClose: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRequestCashierShiftClose, input),
    decideRetailCashierShiftClose: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideCashierShiftClose, input),
    requestRetailCashierShiftVarianceResolution: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRequestCashierShiftVarianceResolution, input),
    decideRetailCashierShiftVarianceResolution: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideCashierShiftVarianceResolution, input),
    createRetailReturnRequest: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateReturnRequest, input),
    createRetailExchange: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateExchange, input),
    decideRetailExchange: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideExchange, input),
    prepareRetailCreditNoteReconciliation: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPrepareCreditNoteReconciliation, input),
    recordRetailCreditNotePortalResponse: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRecordCreditNotePortalResponse, input),
    createRetailInterBranchTransfer: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateInterBranchTransfer, input),
    decideRetailInterBranchTransfer: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideInterBranchTransfer, input),
    dispatchRetailInterBranchTransfer: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDispatchInterBranchTransfer, input),
    receiveRetailInterBranchTransfer: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailReceiveInterBranchTransfer, input),
    createRetailScaleProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateScaleProfile, input),
    createRetailPrinterAdapter: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreatePrinterAdapter, input),
    testRetailPrinterAdapter: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailTestPrinterAdapter, input),
    createRetailLabelPrintDispatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateLabelPrintDispatch, input),
    decideRetailLabelPrintDispatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideLabelPrintDispatch, input),
    prepareRetailCatalogBulkEdit: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPrepareCatalogBulkEdit, input),
    applyRetailCatalogBulkEdit: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailApplyCatalogBulkEdit, input),
    createRetailPurchaseOcrDocument: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreatePurchaseOcrDocument, input),
    decideRetailPurchaseOcr: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecidePurchaseOcr, input),
    convertRetailPurchaseOcr: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailConvertPurchaseOcr, input),
    createRetailCommerceConnector: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCommerceConnector, input),
    configureRetailCommerceCredentials: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailConfigureCommerceCredentials, input),
    createRetailCommerceSyncRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCommerceSyncRun, input),
    executeRetailCommerceSync: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailExecuteCommerceSync, input),
    recordRetailCommerceSync: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRecordCommerceSync, input),
    importRetailCommerceOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailImportCommerceOrder, input),
    handoffRetailCommerceOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailHandoffCommerceOrder, input),
    reserveRetailCommerceOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailReserveCommerceOrder, input),
    createRetailSettlementReconciliation: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateSettlementReconciliation, input),
    decideRetailSettlementReconciliation: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideSettlementReconciliation, input),
    createRetailSettlementAllocationPack: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateSettlementAllocationPack, input),
    decideRetailSettlementAllocationPack: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideSettlementAllocationPack, input),
    createRetailCommerceConflictResolution: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCommerceConflictResolution, input),
    decideRetailCommerceConflictResolution: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideCommerceConflictResolution, input),
    createRetailSettlementWithholdingEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateSettlementWithholdingEvidence, input),
    decideRetailSettlementWithholdingEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideSettlementWithholdingEvidence, input),
    prepareRetailSettlementJournal: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPrepareSettlementJournal, input),
    linkRetailCommerceReturn: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailLinkCommerceReturn, input),
    createRetailOcrProviderProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateOcrProviderProfile, input),
    configureRetailOcrProvider: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailConfigureOcrProvider, input),
    executeRetailOcr: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailExecuteOcr, input),
    testRetailOcrProvider: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailTestOcrProvider, input),
    prepareRetailPurchaseOcrMapping: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPreparePurchaseOcrMapping, input),
    applyRetailPurchaseOcrMapping: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailApplyPurchaseOcrMapping, input),
    prepareRetailCommercePushBatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPrepareCommercePushBatch, input),
    decideRetailCommercePushBatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideCommercePushBatch, input),
    executeRetailCommercePushBatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailExecuteCommercePushBatch, input),
    createRetailCommerceCatalogMapping: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCommerceCatalogMapping, input),
    decideRetailCommerceCatalogMapping: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideCommerceCatalogMapping, input),
    disableRetailCommerceCatalogMapping: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDisableCommerceCatalogMapping, input),
    transitionRetailCommerceOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailTransitionCommerceOrder, input),
    createRetailCommerceConformanceCase: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCommerceConformanceCase, input),
    planRetailCommerceConformancePack: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailPlanCommerceConformancePack, input),
    recordRetailCommerceConformance: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRecordCommerceConformance, input),
    scanRetailPurchaseExceptions: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailScanPurchaseExceptions, input),
    resolveRetailPurchaseException: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailResolvePurchaseException, input),
    inspectRetailReturn: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailInspectReturn, input),
    decideRetailReturn: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideReturn, input),
    requestRetailReturnSettlement: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailRequestReturnSettlement, input),
    decideRetailReturnSettlement: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailDecideReturnSettlement, input),
    confirmRetailReturnProviderRefund: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailConfirmReturnProviderRefund, input),
    createRetailCatalogCategory: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCatalogCategory, input),
    createRetailCatalogBrand: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateCatalogBrand, input),
    saveRetailMerchandisingProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailSaveMerchandisingProfile, input),
    createRetailBarcodeSequence: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateBarcodeSequence, input),
    resetRetailBarcodeSequence: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailResetBarcodeSequence, input),
    assignRetailBarcode: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailAssignBarcode, input),
    createRetailLabelPrintRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateLabelPrintRun, input),
    createRetailProductCombo: (input) => ipcRenderer.invoke(IPC_CHANNELS.retailCreateProductCombo, input),
    recordDeliveryEvidence: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsRecordDeliveryEvidence, input),
    createServiceMilestone: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateServiceMilestone, input),
    transitionServiceMilestone: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsTransitionServiceMilestone, input),
    createInvoiceDraft: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateInvoiceDraft, input),
    issueInvoice: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsIssueInvoice, input),
    createCreditDebitNote: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateCreditDebitNote, input),
    recordPayment: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsRecordPayment, input),
    applyUnappliedReceipt: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsApplyUnappliedReceipt, input),
    reconcilePayment: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsReconcilePayment, input),
    exportJournal: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsExportJournal, input),
    exportInvoicePdf: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsExportInvoicePdf, input),
    createGstRegistration: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateGstRegistration, input),
    createPlaceOfSupplyReview: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreatePlaceOfSupplyReview, input),
    decidePlaceOfSupplyReview: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsDecidePlaceOfSupplyReview, input),
    createStockLocation: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateStockLocation, input),
    recordStockMovement: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsRecordStockMovement, input),
    reserveStock: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsReserveStock, input),
    releaseStockReservation: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsReleaseStockReservation, input),
    createPincodeServiceabilityRule: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreatePincodeServiceabilityRule, input),
    decidePincodeServiceabilityRule: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsDecidePincodeServiceabilityRule, input),
    createDeliveryPromise: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateDeliveryPromise, input),
    createCodCollectionCase: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateCodCollectionCase, input),
    recordCodHandover: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsRecordCodHandover, input),
    recordCodCarrierCollection: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsRecordCodCarrierCollection, input),
    recordCodRemittance: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeRecordCodRemittance, input),
    matchCodBank: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeMatchCodBank, input),
    closeCodShortfall: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeCloseCodShortfall, input),
    recordCodException: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsRecordCodException, input),
    createShipmentPackage: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateShipmentPackage, input),
    transitionShipment: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsTransitionShipment, input),
    configureCarrierAdapter: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsConfigureCarrierAdapter, input),
    createReturnAuthorization: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsCreateReturnAuthorization, input),
    decideReturnAuthorization: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsDecideReturnAuthorization, input),
    receiveReturn: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsReceiveReturn, input),
    inspectReturn: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsInspectReturn, input),
    prepareStatutoryExchange: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsPrepareStatutoryExchange, input),
    submitStatutoryExchange: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsSubmitStatutoryExchange, input),
    recordStatutoryResponse: (input) => ipcRenderer.invoke(IPC_CHANNELS.revenueOpsRecordStatutoryResponse, input),
    configureStatutoryAdapter: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutoryConfigureAdapter, input),
    configureStatutoryCredentials: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutoryConfigureCredentials, input),
    prepareStatutoryOperation: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutoryPrepareOperation, input),
    submitStatutoryOperation: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutorySubmitOperation, input),
    recordStatutoryOperationResponse: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutoryRecordOperationResponse, input),
    prepareConsolidatedEwayBill: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutoryPrepareConsolidatedEwb, input),
    submitConsolidatedEwayBill: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutorySubmitConsolidatedEwb, input),
    recordConsolidatedEwayBillResponse: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutoryRecordConsolidatedEwbResponse, input),
    verifyStatutorySignature: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutoryVerifySignature, input),
    runPortalReconciliation: (input) => ipcRenderer.invoke(IPC_CHANNELS.statutoryRunPortalReconciliation, input),
    configureProviderConnector: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerConfigureConnector, input),
    configureProviderCredentials: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerConfigureCredentials, input),
    createProviderConformanceCase: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerCreateConformanceCase, input),
    planProviderConformancePack: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerPlanConformancePack, input),
    executeProviderPreflight: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerExecutePreflight, input),
    recordProviderConformanceResult: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerRecordConformanceResult, input),
    approveProviderConnector: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerApproveConnector, input),
    prepareProviderSubmission: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerPrepareSubmission, input),
    handOffProviderSubmission: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerHandOffSubmission, input),
    recordProviderSubmissionResponse: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerRecordSubmissionResponse, input),
    runProviderReconciliation: (input) => ipcRenderer.invoke(IPC_CHANNELS.providerRunReconciliation, input),
    proposeCreditLimit: (input) => ipcRenderer.invoke(IPC_CHANNELS.collectionsProposeCreditLimit, input),
    decideCreditLimit: (input) => ipcRenderer.invoke(IPC_CHANNELS.collectionsDecideCreditLimit, input),
    runDunning: (input) => ipcRenderer.invoke(IPC_CHANNELS.collectionsRunDunning, input),
    recordCollectionActivity: (input) => ipcRenderer.invoke(IPC_CHANNELS.collectionsRecordActivity, input),
    openReceivableDispute: (input) => ipcRenderer.invoke(IPC_CHANNELS.collectionsOpenDispute, input),
    resolveReceivableDispute: (input) => ipcRenderer.invoke(IPC_CHANNELS.collectionsResolveDispute, input),
    requestWriteOff: (input) => ipcRenderer.invoke(IPC_CHANNELS.collectionsRequestWriteOff, input),
    decideWriteOff: (input) => ipcRenderer.invoke(IPC_CHANNELS.collectionsDecideWriteOff, input),
    createWithholdingPolicy: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeCreateWithholdingPolicy, input),
    recordWithholdingEntry: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeRecordWithholdingEntry, input),
    transitionWithholdingEntry: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeTransitionWithholdingEntry, input),
    prepareZeroRatedSupply: (input) => ipcRenderer.invoke(IPC_CHANNELS.financePrepareZeroRatedSupply, input),
    decideZeroRatedSupply: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeDecideZeroRatedSupply, input),
    createBankAccount: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeCreateBankAccount, input),
    previewBankStatement: (input) => ipcRenderer.invoke(IPC_CHANNELS.financePreviewBankStatement, input),
    commitBankStatement: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeCommitBankStatement, input),
    confirmBankMatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeConfirmBankMatch, input),
    excludeBankLine: (input) => ipcRenderer.invoke(IPC_CHANNELS.financeExcludeBankLine, input),
    createPurchaseRequisition: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementCreateRequisition, input),
    decidePurchaseRequisition: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementDecideRequisition, input),
    createRfqFromRequisition: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementCreateRfqFromRequisition, input),
    createSupplier: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementCreateSupplier, input),
    decideSupplier: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementDecideSupplier, input),
    createRfq: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementCreateRfq, input),
    issueRfq: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementIssueRfq, input),
    recordSupplierQuotation: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementRecordQuotation, input),
    awardRfq: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementAwardRfq, input),
    createPurchaseOrderFromRfq: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementCreatePoFromRfq, input),
    createPurchaseOrderFromReorder: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementCreatePoFromReorder, input),
    decidePurchaseOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementDecidePo, input),
    recordGoodsReceipt: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementRecordGoodsReceipt, input),
    createLandedCost: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementCreateLandedCost, input),
    decideLandedCost: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementDecideLandedCost, input),
    updateRetailPriceForTargetMargin: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementUpdateRetailPriceForTargetMargin, input),
    recordSupplierInvoice: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementRecordSupplierInvoice, input),
    decideThreeWayMatch: (input) => ipcRenderer.invoke(IPC_CHANNELS.procurementDecideThreeWayMatch, input),
    recordTreasuryPosition: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryRecordPosition, input),
    runCashForecast: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryRunCashForecast, input),
    createPaymentProposal: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryCreatePaymentProposal, input),
    decidePaymentProposal: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryDecidePaymentProposal, input),
    releasePaymentProposal: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryReleasePaymentProposal, input),
    settlePaymentProposal: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasurySettlePaymentProposal, input),
    recordBankCharge: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryRecordBankCharge, input),
    reconcileBankCharge: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryReconcileBankCharge, input),
    openSettlementException: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryOpenSettlementException, input),
    resolveSettlementException: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryResolveSettlementException, input),
    createLiquiditySweep: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryCreateLiquiditySweep, input),
    decideLiquiditySweep: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryDecideLiquiditySweep, input),
    releaseLiquiditySweep: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasuryReleaseLiquiditySweep, input),
    settleLiquiditySweep: (input) => ipcRenderer.invoke(IPC_CHANNELS.treasurySettleLiquiditySweep, input),
    createWorkCenter: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingCreateWorkCenter, input),
    createBomRevision: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingCreateBomRevision, input),
    decideBomRevision: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingDecideBomRevision, input),
    createQualityPlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingCreateQualityPlan, input),
    decideQualityPlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingDecideQualityPlan, input),
    createWorkOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingCreateWorkOrder, input),
    decideWorkOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingDecideWorkOrder, input),
    startWorkOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingStartWorkOrder, input),
    issueWorkOrderMaterial: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingIssueMaterial, input),
    recordQualityInspection: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingRecordInspection, input),
    resolveNonconformance: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingResolveNonconformance, input),
    recordProductionOutput: (input) => ipcRenderer.invoke(IPC_CHANNELS.manufacturingRecordOutput, input),
    createAssetCategory: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateCategory, input),
    createManagedAsset: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateManagedAsset, input),
    submitManagedAsset: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetSubmitManagedAsset, input),
    decideManagedAsset: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideManagedAsset, input),
    createAssetCapitalization: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateCapitalization, input),
    decideAssetCapitalization: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideCapitalization, input),
    createAssetDepreciationPolicy: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateDepreciationPolicy, input),
    decideAssetDepreciationPolicy: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideDepreciationPolicy, input),
    createAssetDepreciationRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateDepreciationRun, input),
    decideAssetDepreciationRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideDepreciationRun, input),
    createAssetRetirement: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateRetirement, input),
    decideAssetRetirement: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideRetirement, input),
    completeAssetRetirement: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCompleteRetirement, input),
    createAssetCustodyTransfer: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateCustodyTransfer, input),
    decideAssetCustodyTransfer: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideCustodyTransfer, input),
    receiveAssetCustodyTransfer: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetReceiveCustodyTransfer, input),
    createAssetComponentization: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateComponentization, input),
    decideAssetComponentization: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideComponentization, input),
    createAssetComponentAllocation: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateComponentAllocation, input),
    decideAssetComponentAllocation: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideComponentAllocation, input),
    createAssetTransferAccounting: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateTransferAccounting, input),
    decideAssetTransferAccounting: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideTransferAccounting, input),
    dispatchAssetTransferAccounting: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDispatchTransferAccounting, input),
    receiveAssetTransferAccounting: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetReceiveTransferAccounting, input),
    createAssetSaleDisposal: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCreateSaleDisposal, input),
    decideAssetSaleDisposal: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetDecideSaleDisposal, input),
    completeAssetSaleDisposal: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetCompleteSaleDisposal, input),
    runAssetLifecycleAction: (input) => ipcRenderer.invoke(IPC_CHANNELS.assetRunLifecycleAction, input),
    createPreventiveMaintenancePlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.maintenanceCreatePreventivePlan, input),
    generateDueMaintenanceWorkOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.maintenanceGenerateDueWorkOrder, input),
    startMaintenanceWorkOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.maintenanceStartWorkOrder, input),
    completeMaintenanceWorkOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.maintenanceCompleteWorkOrder, input),
    verifyMaintenanceWorkOrder: (input) => ipcRenderer.invoke(IPC_CHANNELS.maintenanceVerifyWorkOrder, input),
    createProject: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryCreateProject, input),
    decideProject: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryDecideProject, input),
    transitionProject: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryTransitionProject, input),
    createProjectTask: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryCreateTask, input),
    transitionProjectTask: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryTransitionTask, input),
    recordTimeEntry: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryRecordTime, input),
    decideTimeEntry: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryDecideTime, input),
    createServiceAgreement: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryCreateAgreement, input),
    decideServiceAgreement: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryDecideAgreement, input),
    createSupportTicket: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryCreateTicket, input),
    transitionSupportTicket: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryTransitionTicket, input),
    createFieldServiceJob: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryCreateFieldJob, input),
    transitionFieldServiceJob: (input) => ipcRenderer.invoke(IPC_CHANNELS.deliveryTransitionFieldJob, input),
    createWorkforceProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceCreateProfile, input),
    decideWorkforceProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceDecideProfile, input),
    recordWorkforceAvailability: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceRecordAvailability, input),
    decideWorkforceAvailability: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceDecideAvailability, input),
    createWorkforceAllocation: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceCreateAllocation, input),
    cancelWorkforceAllocation: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceCancelAllocation, input),
    createEmployerRegistration: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollCreateRegistration, input),
    decideEmployerRegistration: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollDecideRegistration, input),
    createPayrollPolicy: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollCreatePolicy, input),
    decidePayrollPolicy: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollDecidePolicy, input),
    createPayrollCompensation: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollCreateCompensation, input),
    decidePayrollCompensation: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollDecideCompensation, input),
    createBenefitPlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollCreateBenefitPlan, input),
    decideBenefitPlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollDecideBenefitPlan, input),
    createBenefitEnrollment: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollCreateBenefitEnrollment, input),
    decideBenefitEnrollment: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollDecideBenefitEnrollment, input),
    createPayrollRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollCreateRun, input),
    decidePayrollRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollDecideRun, input),
    finalizePayrollRun: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollFinalizeRun, input),
    updatePayrollObligation: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollUpdateObligation, input),
    createExpenseClaim: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollCreateExpense, input),
    decideExpenseClaim: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollDecideExpense, input),
    reimburseExpenseClaim: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollReimburseExpense, input),
    recordAttendance: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceRecordAttendance, input),
    decideAttendance: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceDecideAttendance, input),
    createLeaveType: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceCreateLeaveType, input),
    decideLeaveType: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceDecideLeaveType, input),
    createLeaveApplication: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceCreateLeaveApplication, input),
    decideLeaveApplication: (input) => ipcRenderer.invoke(IPC_CHANNELS.workforceDecideLeaveApplication, input),
    createPayrollAdjustment: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollCreateAdjustment, input),
    decidePayrollAdjustment: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollDecideAdjustment, input),
    createTaxDeclaration: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollCreateTaxDeclaration, input),
    decideTaxDeclaration: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollDecideTaxDeclaration, input),
    publishPayslip: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollPublishPayslip, input),
    acknowledgePayslip: (input) => ipcRenderer.invoke(IPC_CHANNELS.payrollAcknowledgePayslip, input),
    createProjectBillingPlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.financialCreateBillingPlan, input),
    decideProjectBillingPlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.financialDecideBillingPlan, input),
    createProjectBillingClaim: (input) => ipcRenderer.invoke(IPC_CHANNELS.financialCreateBillingClaim, input),
    decideProjectBillingClaim: (input) => ipcRenderer.invoke(IPC_CHANNELS.financialDecideBillingClaim, input),
    consumeServiceEntitlement: (input) => ipcRenderer.invoke(IPC_CHANNELS.financialConsumeEntitlement, input),
    createAccountingClosePeriod: (input) => ipcRenderer.invoke(IPC_CHANNELS.financialCreateClosePeriod, input),
    decideAccountingClosePeriod: (input) => ipcRenderer.invoke(IPC_CHANNELS.financialDecideClosePeriod, input),
    reopenAccountingClosePeriod: (input) => ipcRenderer.invoke(IPC_CHANNELS.financialReopenClosePeriod, input),
    createProjectExchangeRate: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialCreateExchangeRate, input),
    decideProjectExchangeRate: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialDecideExchangeRate, input),
    createProjectCurrencyProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialCreateCurrencyProfile, input),
    decideProjectCurrencyProfile: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialDecideCurrencyProfile, input),
    createProjectContractVariation: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialCreateVariation, input),
    decideProjectContractVariation: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialDecideVariation, input),
    createProjectRetainer: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialCreateRetainer, input),
    decideProjectRetainer: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialDecideRetainer, input),
    createRetainerDrawdown: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialCreateDrawdown, input),
    decideRetainerDrawdown: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialDecideDrawdown, input),
    createProjectResourcePlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialCreateResourcePlan, input),
    decideProjectResourcePlan: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialDecideResourcePlan, input),
    generateProjectMarginReview: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialGenerateMarginReview, input),
    reviewProjectMargin: (input) => ipcRenderer.invoke(IPC_CHANNELS.commercialReviewMargin, input),
    createUom: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateUom, input),
    createUomConversion: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateUomConversion, input),
    createInventoryItem: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateItem, input),
    createItemVariant: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateVariant, input),
    createWarehouse: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateWarehouse, input),
    createWarehouseZone: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateZone, input),
    createStorageBin: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateBin, input),
    receiveInventory: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryReceive, input),
    createPutawayTask: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreatePutaway, input),
    createPickTask: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreatePick, input),
    transitionWarehouseTask: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryTransitionTask, input),
    createInventoryTransfer: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateTransfer, input),
    transitionInventoryTransfer: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryTransitionTransfer, input),
    createCycleCount: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateCycleCount, input),
    recordCycleCount: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryRecordCycleCount, input),
    decideCycleCount: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryDecideCycleCount, input),
    createReorderPolicy: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateReorderPolicy, input),
    generateReorderProposals: () => ipcRenderer.invoke(IPC_CHANNELS.inventoryGenerateReorderProposals),
    decideReorderProposal: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryDecideReorderProposal, input),
    createInventoryValuationReview: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateValuationReview, input),
    decideInventoryValuationReview: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryDecideValuationReview, input),
    createInventoryDisposition: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryCreateDisposition, input),
    decideInventoryDisposition: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryDecideDisposition, input),
    postInventoryDisposition: (input) => ipcRenderer.invoke(IPC_CHANNELS.inventoryPostDisposition, input),
  },
  crm: {
    getSnapshot: () => ipcRenderer.invoke(IPC_CHANNELS.crmSnapshot),
    createLead: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.crmCreateLead, input),
    moveOpportunity: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.crmMoveOpportunity, input),
    completeActivity: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.crmCompleteActivity, input),
  },
  kernel: {
    getSnapshot: () => ipcRenderer.invoke(IPC_CHANNELS.kernelSnapshot),
    getOperationalHealth: () => ipcRenderer.invoke(IPC_CHANNELS.kernelOperationalHealth),
    getOutboxReplayPlan: () => ipcRenderer.invoke(IPC_CHANNELS.kernelOutboxReplayPlan),
    executeOutboxReplay: (input) => ipcRenderer.invoke(IPC_CHANNELS.kernelExecuteOutboxReplay, input),
    resolveOutboxConflict: (input) => ipcRenderer.invoke(IPC_CHANNELS.kernelResolveOutboxConflict, input),
    updateTenantIdentity: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelUpdateTenantIdentity, input),
    createCompany: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelCreateCompany, input),
    updateCompany: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelUpdateCompany, input),
    createBranch: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelCreateBranch, input),
    updateBranch: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelUpdateBranch, input),
    createUser: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelCreateUser, input),
    createRole: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelCreateRole, input),
    updateRolePolicy: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelUpdateRolePolicy, input),
    upsertFieldAccessRule: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelUpsertFieldAccessRule, input),
    updateApprovalPolicy: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelUpdateApprovalPolicy, input),
    assignRole: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelAssignRole, input),
    issueNumber: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelIssueNumber, input),
    transitionWorkflow: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelTransitionWorkflow, input),
    decideApproval: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelDecideApproval, input),
    registerCustomField: (input) =>
      ipcRenderer.invoke(IPC_CHANNELS.kernelRegisterCustomField, input),
  },
};

contextBridge.exposeInMainWorld('epicBos', bridge);
