import { MapPin, Store, Users, WifiOff } from 'lucide-react';
import type { ReactNode } from 'react';
import type { RetailHubCoverageMap } from '../shared/retail-hub-coverage-map-contracts';

function axis(value: number, min: number, range: number): number { return range === 0 ? 50 : ((value - min) / range) * 100; }

export function RetailCoverageMapSurface({ coverage }: { coverage?: RetailHubCoverageMap }): ReactNode {
  if (!coverage) return <article className="retail-coverage-map" data-testid="retail-coverage-map" data-status="unavailable"><header><span className="eyebrow"><MapPin size={14} aria-hidden="true" /> Bakaloo coverage</span><h3>Load your real store coverage</h3><p>This map stays empty until the authenticated Retail Hub returns the live shop/customer projection. No demo pins are shown.</p></header><div className="retail-coverage-map__empty"><WifiOff size={20} aria-hidden="true" /><span>Connect the Bakaloo Hub from the delivery controls to review serviceable areas.</span></div></article>;
  const points = [{ lat: coverage.shop.lat, lng: coverage.shop.lng }, ...coverage.customers.map(({ lat, lng }) => ({ lat, lng }))];
  const minLat = Math.min(...points.map(({ lat }) => lat));
  const maxLat = Math.max(...points.map(({ lat }) => lat));
  const minLng = Math.min(...points.map(({ lng }) => lng));
  const maxLng = Math.max(...points.map(({ lng }) => lng));
  const latRange = maxLat - minLat;
  const lngRange = maxLng - minLng;
  return <article className="retail-coverage-map" data-testid="retail-coverage-map" data-status="available"><header><div><span className="eyebrow"><MapPin size={14} aria-hidden="true" /> Bakaloo coverage</span><h3>{coverage.shop.name}</h3><p>Read-only customer coverage from {coverage.shop.city}. Pins and boundaries are sourced from the Hub; nothing here writes back.</p></div><span className="retail-coverage-map__scope">{coverage.totalCustomers} customers · {coverage.serviceablePincodes.length} serviceable pincodes</span></header><div className="retail-coverage-map__body"><div className="retail-coverage-map__canvas" role="img" aria-label={`${coverage.totalCustomers} customers around ${coverage.shop.name}`}><svg viewBox="0 0 100 100" aria-hidden="true" preserveAspectRatio="none"><path d="M0 25H100M0 50H100M0 75H100M25 0V100M50 0V100M75 0V100" />{coverage.boundaries.map((boundary) => <polygon key={boundary.pincode} points={boundary.polygon.map(([lat, lng]) => `${axis(lng, minLng, lngRange)},${100 - axis(lat, minLat, latRange)}`).join(' ')} />)}<circle className="retail-coverage-map__shop" cx={axis(coverage.shop.lng, minLng, lngRange)} cy={100 - axis(coverage.shop.lat, minLat, latRange)} r="3.5" />{coverage.customers.map((customer) => <circle key={customer.userId} className="retail-coverage-map__customer" data-active-order={customer.hasActiveOrder ? 'true' : 'false'} cx={axis(customer.lng, minLng, lngRange)} cy={100 - axis(customer.lat, minLat, latRange)} r="2.3" />)}</svg><span className="retail-coverage-map__legend"><Store size={12} aria-hidden="true" /> store <Users size={12} aria-hidden="true" /> customers <span>· live Hub snapshot</span></span></div><div className="retail-coverage-map__register"><div><Store size={15} aria-hidden="true" /><strong>{coverage.shop.pincode}</strong><small>Store pin · {coverage.shop.state}</small></div><div><Users size={15} aria-hidden="true" /><strong>{coverage.totalCustomers}</strong><small>Covered customer locations</small></div><div><WifiOff size={15} aria-hidden="true" /><strong>{coverage.uncoveredPincodes.length}</strong><small>Serviceable pincodes without customers</small></div></div></div><footer>Observed {new Date(coverage.observedAt).toLocaleString('en-IN')} · scope {coverage.scope.companyId}/{coverage.scope.branchId}</footer></article>;
}
